# Generated by Django 5.2.9 on 2026-01-12 08:36

import django.db.models.deletion
import django.utils.timezone
import media_derivatives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDerivative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_slug', models.SlugField(default='hero_mobile_v1', help_text='Derivative profile identifier (e.g. hero_mobile_v1).', max_length=64)),
                ('kind', models.CharField(choices=[('webm', 'WebM'), ('mp4', 'MP4'), ('other', 'Other')], default='webm', help_text='What type of derivative this row represents.', max_length=16)),
                ('file', models.FileField(blank=True, help_text='The generated derivative file (e.g. .webm or .mp4).', null=True, upload_to=media_derivatives.models._derived_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('source_etag', models.CharField(blank=True, default='', help_text='Optional: etag or content fingerprint of the source Document file at time of processing.', max_length=128)),
                ('error', models.TextField(blank=True, default='', help_text='If processing failed, store a human-readable error message here.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The original uploaded Wagtail Document this derivative was produced from.', on_delete=django.db.models.deletion.CASCADE, related_name='video_derivatives', to='wagtaildocs.document')),
                ('poster_image', models.ForeignKey(blank=True, help_text='Optional poster image generated from the video (stored as a Wagtail Image).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'profile_slug'], name='media_deriv_documen_e96bce_idx'), models.Index(fields=['status'], name='media_deriv_status_a15d45_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'profile_slug', 'kind'), name='uniq_video_derivative_per_doc_profile_kind')],
            },
        ),
    ]
