# Generated by Django 5.2.9 on 2026-01-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_derivatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoderivative',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoderivative',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 progress for this derivative generation.'),
        ),
        migrations.AddField(
            model_name='videoderivative',
            name='rq_job_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='RQ job id for the job currently/last producing this derivative.', max_length=64),
        ),
        migrations.AddField(
            model_name='videoderivative',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
