# Generated by Django 5.2.9 on 2026-01-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_derivatives', '0002_videoderivative_finished_at_videoderivative_progress_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoderivative',
            index=models.Index(fields=['document', 'profile_slug', 'kind'], name='idx_derivative_lookup'),
        ),
    ]
