# Generated by Django 5.2.9 on 2025-12-30 08:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('hero', 6), ('text_image', 12), ('reviews_slider', 19), ('cta', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your best skin, on the menu', 'help_text': 'Short, confident headline. Aim for one line on desktop.', 'max_length': 80, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'One short paragraph max. Keep it clean and editorial.', 'max_length': 240, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional. Avoid needles; prefer skin/clinic/editorial.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('primary_cta', 4), ('secondary_cta', 4), ('image', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional small label above the heading.', 'max_length': 40, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Keep paragraphs short. No long walls of copy.', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 7), ('heading', 8), ('body', 9), ('image', 10), ('image_position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Reviews', 'max_length': 60, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Google', 'max_length': 40, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('quote', 14), ('author', 15), ('source', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 12, 'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('heading', 13), ('reviews', 18)]], {}), 20: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': True}), 22: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 20), ('primary_cta', 21), ('secondary_cta', 4)]], {})}),
        ),
    ]
