# Generated by Django 5.2.9 on 2026-01-04 08:38

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_standardpage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional short introduction shown near the top.')),
                ('sections', wagtail.fields.StreamField([('rich_text_section', 3), ('text_image', 7), ('key_facts', 12), ('steps', 17), ('faq', 22), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 4), ('body', 2), ('image', 5), ('image_position', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Key facts', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 8, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 8), ('facts', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'What to expect', 'max_length': 80, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 8, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 13), ('steps', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('question', 19), ('answer', 2)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 20, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 18), ('items', 21)]], {}), 23: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 23), ('primary_cta', 25), ('secondary_cta', 26)]], {})})),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional intro text for the journal landing page.')),
            ],
            options={
                'verbose_name': 'Blog index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional short intro shown above details.')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.TextField(blank=True, help_text='Plain text opening hours (e.g. Mon–Fri 10–7).')),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional Google Maps embed URL (iframe src).')),
                ('sections', wagtail.fields.StreamField([('rich_text_section', 3), ('text_image', 7), ('key_facts', 12), ('steps', 17), ('faq', 22), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 4), ('body', 2), ('image', 5), ('image_position', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Key facts', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 8, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 8), ('facts', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'What to expect', 'max_length': 80, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 8, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 13), ('steps', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('question', 19), ('answer', 2)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 20, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 18), ('items', 21)]], {}), 23: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 23), ('primary_cta', 25), ('secondary_cta', 26)]], {})})),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TreatmentsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional editorial intro for the treatments landing page.')),
                ('sections', wagtail.fields.StreamField([('rich_text_section', 3), ('text_image', 7), ('key_facts', 12), ('steps', 17), ('faq', 22), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 4), ('body', 2), ('image', 5), ('image_position', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Key facts', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 8, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 8), ('facts', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'What to expect', 'max_length': 80, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 8, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 13), ('steps', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('question', 19), ('answer', 2)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 20, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 18), ('items', 21)]], {}), 23: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 23), ('primary_cta', 25), ('secondary_cta', 26)]], {})})),
            ],
            options={
                'verbose_name': 'Treatments index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('hero', 8), ('treatments', 18), ('text_image', 24), ('reviews_slider', 31), ('cta', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your best skin, on the menu', 'max_length': 80, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bottom_left', 'Bottom left'), ('center', 'Center'), ('bottom_right', 'Bottom right'), ('top_left', 'Top left'), ('top_right', 'Top right')], 'help_text': 'Where the hero text + CTA sits on the image.'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add 1 image for a static hero. Add 2+ for a carousel.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('primary_cta', 4), ('cta_position', 5), ('hero_images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Treatments', 'max_length': 80, 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'max_length': 220, 'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional. If empty, a clean placeholder will be shown.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional short line (e.g. 'Enhance your natural features').", 'max_length': 140, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page', 11), ('image', 12), ('blurb', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Add treatment/category tiles. Each can have an optional image.', 'max_num': 18, 'min_num': 3}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'See full menu', 'max_length': 30, 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Typically the /menu page.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 9), ('intro', 10), ('items', 15), ('cta_label', 16), ('cta_page', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 24: ('wagtail.blocks.StructBlock', [[('eyebrow', 19), ('heading', 20), ('body', 21), ('image', 22), ('image_position', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Client reviews', 'max_length': 60, 'required': False}), 26: ('wagtail.blocks.TextBlock', (), {'max_length': 420, 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('quote', 26), ('author', 27), ('source', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'max_num': 20, 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('heading', 25), ('reviews', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': True}), 33: ('wagtail.blocks.StructBlock', [[('heading', 20), ('body', 1), ('primary_cta', 32), ('secondary_cta', 4)]], {})}),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary used on listings and as meta description fallback.', max_length=240)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('pull_quote', 6), ('faq', 13), ('cta', 20)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.TextBlock', (), {'max_length': 280, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('quote', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('question', 9), ('answer', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 20, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('eyebrow', 7), ('heading', 8), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 17: ('wagtail.blocks.URLBlock', (), {'required': True}), 18: ('wagtail.blocks.StructBlock', [[('label', 16), ('url', 17)]], {'required': True}), 19: ('wagtail.blocks.StructBlock', [[('label', 16), ('url', 17)]], {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('heading', 14), ('body', 15), ('primary_cta', 18), ('secondary_cta', 19)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='pages.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TreatmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('injectables', 'Injectables'), ('skin', 'Skin'), ('laser', 'Laser'), ('body', 'Body'), ('consultation', 'Consultation'), ('other', 'Other')], default='skin', max_length=24)),
                ('summary', models.TextField(blank=True, help_text='One-paragraph summary shown beneath title and used for SEO snippets.', max_length=280)),
                ('duration', models.CharField(blank=True, help_text='e.g., 30–45 minutes', max_length=60)),
                ('downtime', models.CharField(blank=True, help_text='e.g., Minimal / 24–48 hours', max_length=60)),
                ('price_from', models.CharField(blank=True, help_text='e.g., From £180', max_length=40)),
                ('sections', wagtail.fields.StreamField([('rich_text_section', 3), ('text_image', 7), ('key_facts', 12), ('steps', 17), ('faq', 22), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 4), ('body', 2), ('image', 5), ('image_position', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Key facts', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 8, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 8), ('facts', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'What to expect', 'max_length': 80, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 8, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 13), ('steps', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('question', 19), ('answer', 2)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 20, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 18), ('items', 21)]], {}), 23: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 23), ('primary_cta', 25), ('secondary_cta', 26)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Treatment page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
