# Generated by Django 5.2.9 on 2026-01-04 09:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_aboutpage_blogindexpage_contactpage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='sections',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='booking_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional small helper text.', 'max_length': 60, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('note', 2)]], {})}, help_text='Buttons to socials / booking portals / external destinations.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Shown after successful form submission.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional short intro shown above the form.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('hero', 8), ('treatments', 18), ('text_image', 24), ('reviews_slider', 31), ('cta', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your best skin, on the menu', 'max_length': 80, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bottom_left', 'Bottom left'), ('center', 'Center'), ('bottom_right', 'Bottom right'), ('top_left', 'Top left'), ('top_right', 'Top right')], 'help_text': 'Where the hero text + CTA sits on the image.'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add 1 image for a static hero. Add 2+ for a carousel.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('primary_cta', 4), ('cta_position', 5), ('hero_images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Treatments', 'max_length': 80, 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'max_length': 220, 'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional. If empty, a clean placeholder will be shown.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short line.', 'max_length': 140, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('page', 11), ('image', 12), ('blurb', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Add treatment/category tiles. Each can have an optional image.', 'max_num': 18, 'min_num': 3}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'See full menu', 'max_length': 30, 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Typically the /menu page.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 9), ('intro', 10), ('items', 15), ('cta_label', 16), ('cta_page', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 24: ('wagtail.blocks.StructBlock', [[('eyebrow', 19), ('heading', 20), ('body', 21), ('image', 22), ('image_position', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Client reviews', 'max_length': 60, 'required': False}), 26: ('wagtail.blocks.TextBlock', (), {'max_length': 420, 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('quote', 26), ('author', 27), ('source', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'max_num': 20, 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('heading', 25), ('reviews', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': True}), 33: ('wagtail.blocks.StructBlock', [[('heading', 20), ('body', 1), ('primary_cta', 32), ('secondary_cta', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='treatmentsindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional editorial intro for the menu landing page.'),
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('experience', models.CharField(blank=True, help_text='e.g. 10+ years • Injectables', max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='pages.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPageFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='pages.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('sections', wagtail.fields.StreamField([('rich_text_section', 3), ('text_image', 7), ('key_facts', 12), ('steps', 17), ('faq', 22), ('cta', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 4), ('body', 2), ('image', 5), ('image_position', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Key facts', 'max_length': 80, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 8, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 8), ('facts', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'What to expect', 'max_length': 80, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 2)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 8, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 13), ('steps', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 80, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('question', 19), ('answer', 2)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'max_num': 20, 'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 18), ('items', 21)]], {}), 23: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('label', 9), ('url', 24)]], {'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 23), ('primary_cta', 25), ('secondary_cta', 26)]], {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Menu section',
            },
            bases=('wagtailcore.page',),
        ),
    ]
