# Generated by Django 5.2.9 on 2026-01-04 13:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_homepage_sections'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutteammember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='treatmentsindexpage',
            options={'verbose_name': 'Menu index'},
        ),
        migrations.RemoveField(
            model_name='aboutteammember',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='downtime',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='price_from',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='treatmentsindexpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional intro shown under the title.'),
        ),
        migrations.AlterField(
            model_name='aboutteammember',
            name='experience',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional Google Maps embed URL (iframe src). Paste only the iframe src value.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='menusectionpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional editorial intro for this menu section.'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatmentpage',
            name='summary',
            field=models.TextField(blank=True, help_text='One paragraph summary for the top of the page.', max_length=240),
        ),
        migrations.AlterField(
            model_name='treatmentsindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional intro text shown under the title.'),
        ),
    ]
