# Generated by Django 5.2.9 on 2026-01-04 22:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_treatmentpage_hero_alter_menusectionpage_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusectionpage',
            name='hero',
            field=wagtail.fields.StreamField([('hero_block', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your best skin, on the menu', 'max_length': 80, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('url', 3)]], {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bottom_left', 'Bottom left'), ('center', 'Center'), ('bottom_right', 'Bottom right'), ('top_left', 'Top left'), ('top_right', 'Top right')], 'help_text': 'Where the hero text + CTA sits on the image.'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image (used as poster / fallback; can be used together with video).', 'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Optional video file (upload an .mp4 to Documents, then select it here).', 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Loop video playback.', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0.75', '0.75× (slow)'), ('1.0', '1.0× (normal)'), ('1.25', '1.25× (fast)'), ('1.5', '1.5× (fast)')], 'help_text': 'Playback speed (applied via JS).', 'required': False}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Horizontal focus (0-100).', 'max_value': 100, 'min_value': 0, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Vertical focus (0-100).', 'max_value': 100, 'min_value': 0, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 6), ('video', 7), ('loop', 8), ('playback_rate', 9), ('pos_x', 10), ('pos_y', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Add 1 item for a static hero. Add 2+ for a carousel. Each slide can be an image or a video file.', 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': "Legacy images-only hero. Prefer using 'Hero media' above for video support.", 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('primary_cta', 4), ('cta_position', 5), ('hero_media', 13), ('hero_images', 15)]], {})}),
        ),
    ]
