# Generated by Django 5.2.9 on 2026-01-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_treatmentcategory_featured_image_and_more'),
        ('pages', '0014_menusectionpage_category_treatmentpage_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusectionpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='treatment',
        ),
        migrations.AddField(
            model_name='menusectionpage',
            name='treatment',
            field=models.ForeignKey(blank=True, help_text='Link this menu section to the normalized treatment record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_pages', to='catalog.treatment'),
        ),
        migrations.AddField(
            model_name='treatmentpage',
            name='option',
            field=models.ForeignKey(blank=True, help_text='Link this page to a normalized treatment option.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_pages', to='catalog.treatmentoption'),
        ),
    ]
