# Generated by Django 5.2.9 on 2026-01-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_menusectionpage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusectionpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='menusectionpage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='treatmentpage',
            name='summary',
        ),
    ]
