# Generated by Django 5.2.9 on 2026-03-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_enforce_option_link_integrity'),
        ('pages', '0016_remove_menusectionpage_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpage',
            name='treatment',
            field=models.ForeignKey(blank=True, help_text='Link this page to a top-level treatment record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_pages', to='catalog.treatment'),
        ),
        migrations.AlterField(
            model_name='treatmentpage',
            name='option',
            field=models.ForeignKey(blank=True, help_text='[Legacy] Link this page to a treatment option.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_pages', to='catalog.treatmentoption'),
        ),
    ]
