# Generated by Django 5.2.9 on 2026-01-22 17:24

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcategory',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatmentcategorycontentblock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='treatmentcategorycontentblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='treatmentfact',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='downtime',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='treatmentfaq',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatmentmedia',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatmentprice',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='treatmentstep',
            name='treatment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='TreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, max_length=300)),
                ('long_description', wagtail.fields.RichTextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('treatment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.treatment')),
            ],
            options={
                'verbose_name': 'Treatment option',
                'verbose_name_plural': 'Treatment options',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='treatmentfaq',
            name='option',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.treatmentoption'),
        ),
        migrations.AddField(
            model_name='treatmentmedia',
            name='option',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.treatmentoption'),
        ),
        migrations.AddField(
            model_name='treatmentprice',
            name='option',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.treatmentoption'),
        ),
        migrations.AddField(
            model_name='treatmentstep',
            name='option',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.treatmentoption'),
        ),
        migrations.CreateModel(
            name='TreatmentOptionContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='catalog.contentblock')),
                ('option', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='catalog.treatmentoption')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentOptionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=160)),
                ('option', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='catalog.treatmentoption')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
