# Generated by Django 5.2.9 on 2026-01-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_treatmentcategory_featured_image_and_more'),
        ('pages', '0015_remove_menusectionpage_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentCategory',
        ),
        migrations.DeleteModel(
            name='TreatmentCategoryContentBlock',
        ),
        migrations.DeleteModel(
            name='TreatmentFact',
        ),
    ]
