# Generated by Django 5.2.9 on 2026-03-11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


def cleanup_orphan_option_children(apps, schema_editor):
    models_to_clean = [
        "TreatmentOptionFact",
        "TreatmentPrice",
        "TreatmentMedia",
        "TreatmentFAQ",
        "TreatmentStep",
        "TreatmentOptionContentBlock",
    ]
    for model_name in models_to_clean:
        model = apps.get_model("catalog", model_name)
        model.objects.filter(option__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_delete_treatmentcategory_and_more"),
    ]

    operations = [
        migrations.RunPython(cleanup_orphan_option_children, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="treatmentfaq",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="catalog.treatmentoption",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentmedia",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="catalog.treatmentoption",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentoptioncontentblock",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_blocks",
                to="catalog.treatmentoption",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentoptionfact",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facts",
                to="catalog.treatmentoption",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentprice",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="catalog.treatmentoption",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentstep",
            name="option",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="catalog.treatmentoption",
            ),
        ),
    ]
