# Generated by Django 5.2.9 on 2025-12-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='SKINMENU', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True, help_text='E.g. Mon–Fri 10:00–19:00')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
