# Generated by Django 5.2.9 on 2025-12-31 11:00

import colorfield.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='GA4 Measurement ID (e.g. G-XXXXXXX). Loaded only with analytics consent.', max_length=32)),
                ('meta_pixel_id', models.CharField(blank=True, help_text='Meta Pixel ID. Loaded only with marketing consent.', max_length=32)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='BrandAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light_path', models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-08.svg', max_length=255)),
                ('logo_dark_path', models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-09.svg', max_length=255)),
                ('mark_light_path', models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-02.svg', max_length=255)),
                ('mark_dark_path', models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-03.svg', max_length=255)),
                ('light_bg', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('light_fg', colorfield.fields.ColorField(default='#261b16', image_field=None, max_length=25, samples=None)),
                ('light_surface', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('light_surface_2', colorfield.fields.ColorField(default='#f5f2ee', image_field=None, max_length=25, samples=None)),
                ('light_border', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('light_muted', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('light_heading', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('light_accent', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('light_accent_2', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('dark_bg', colorfield.fields.ColorField(default='#261b16', image_field=None, max_length=25, samples=None)),
                ('dark_fg', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('dark_surface', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('dark_surface_2', colorfield.fields.ColorField(default='#4d2621', image_field=None, max_length=25, samples=None)),
                ('dark_border', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_muted', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_heading', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('dark_accent', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_accent_2', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Brand appearance',
            },
        ),
        migrations.CreateModel(
            name='GlobalSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='SKINMENU', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True, help_text='E.g. Mon–Fri 10:00–19:00')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True, help_text='Optional: link to Google Maps location (for footer + contact).')),
                ('newsletter_heading', models.CharField(blank=True, default='Stay in the know', max_length=80)),
                ('newsletter_copy', models.CharField(blank=True, default='Enter your email to stay in the know', max_length=180)),
                ('newsletter_form_action', models.URLField(blank=True, help_text='Optional: external newsletter form endpoint (Mailchimp/ConvertKit). Leave blank to hide the form.')),
                ('newsletter_button_label', models.CharField(blank=True, default='Subscribe', max_length=40)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Prefer selecting a page.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use only if linking off-site.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})}, help_text='Top-level navigation links.')),
                ('menu_label', models.CharField(blank=True, default='The Menu', max_length=30)),
                ('menu_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Prefer selecting a page.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use only if linking off-site.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})}, help_text="Dropdown links under 'The Menu'.")),
                ('header_cta', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Prefer selecting a page.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use only if linking off-site.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})}, help_text='Optional single CTA button in header (e.g. Enquire).')),
                ('footer_links', wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Prefer selecting a page.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use only if linking off-site.', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2), ('open_in_new_tab', 3)]], {})}, help_text='Footer links column (e.g. About, Journal, Contact, Privacy).')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
    ]
