# Generated by Django 5.2.9 on 2025-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='newsletter_button_label',
            field=models.CharField(blank=True, default='Subscribe', max_length=40),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='newsletter_copy',
            field=models.CharField(blank=True, default='Enter your email to stay in the know', max_length=180),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='newsletter_form_action',
            field=models.URLField(blank=True, help_text='Optional: external newsletter form endpoint (Mailchimp/ConvertKit). Leave blank to hide the form.'),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='newsletter_heading',
            field=models.CharField(blank=True, default='Stay in the know', max_length=80),
        ),
    ]
