# Generated by Django 5.2.9 on 2026-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandappearancesettings',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={},
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps embed URL (iframe src) for the footer map.', max_length=2000),
        ),
        migrations.DeleteModel(
            name='AnalyticsSettings',
        ),
        migrations.DeleteModel(
            name='BrandAppearanceSettings',
        ),
    ]
