# Generated by Django 5.2.9 on 2025-12-31 08:26

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_globalsitesettings_newsletter_button_label_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light_path', models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-09.svg', max_length=255)),
                ('logo_dark_path', models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-07.svg', max_length=255)),
                ('mark_light_path', models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-01.svg', max_length=255)),
                ('mark_dark_path', models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-04.svg', max_length=255)),
                ('light_bg', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('light_fg', colorfield.fields.ColorField(default='#261b16', image_field=None, max_length=25, samples=None)),
                ('light_surface', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('light_surface_2', colorfield.fields.ColorField(default='#f5f2ee', image_field=None, max_length=25, samples=None)),
                ('light_border', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('light_muted', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('light_heading', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('light_accent', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('light_accent_2', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('dark_bg', colorfield.fields.ColorField(default='#261b16', image_field=None, max_length=25, samples=None)),
                ('dark_fg', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('dark_surface', colorfield.fields.ColorField(default='#3d2b1f', image_field=None, max_length=25, samples=None)),
                ('dark_surface_2', colorfield.fields.ColorField(default='#4d2621', image_field=None, max_length=25, samples=None)),
                ('dark_border', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_muted', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_heading', colorfield.fields.ColorField(default='#e5e0d6', image_field=None, max_length=25, samples=None)),
                ('dark_accent', colorfield.fields.ColorField(default='#b8a693', image_field=None, max_length=25, samples=None)),
                ('dark_accent_2', colorfield.fields.ColorField(default='#786050', image_field=None, max_length=25, samples=None)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Brand appearance',
            },
        ),
    ]
