# Generated by Django 5.2.9 on 2025-12-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_brandappearancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='logo_dark_path',
            field=models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-09.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='logo_light_path',
            field=models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09'), ('brand/primary/Logo-10.svg', 'Primary Logo 10'), ('brand/primary/Logo-11.svg', 'Primary Logo 11'), ('brand/primary/Logo-12.svg', 'Primary Logo 12')], default='brand/primary/Logo-08.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='mark_dark_path',
            field=models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-03.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='mark_light_path',
            field=models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Mark 03'), ('brand/brand_mark/Logo-04.svg', 'Mark 04'), ('brand/brand_mark/Logo-05.svg', 'Mark 05'), ('brand/brand_mark/Logo-06.svg', 'Mark 06')], default='brand/brand_mark/Logo-02.svg', max_length=255),
        ),
    ]
