# Generated by Django 5.2.9 on 2026-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_navigationsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsitesettings',
            options={'verbose_name': 'Global'},
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps iframe *src* URL (not the full iframe tag). Used to render an embed iframe.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='logo_dark_path',
            field=models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09')], default='brand/primary/Logo-09.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='logo_light_path',
            field=models.CharField(choices=[('brand/primary/Logo-07.svg', 'Primary Logo 07'), ('brand/primary/Logo-08.svg', 'Primary Logo 08'), ('brand/primary/Logo-09.svg', 'Primary Logo 09')], default='brand/primary/Logo-08.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='mark_dark_path',
            field=models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Brand Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Brand Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Brand Mark 03')], default='brand/brand_mark/Logo-03.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandappearancesettings',
            name='mark_light_path',
            field=models.CharField(choices=[('brand/brand_mark/Logo-01.svg', 'Brand Mark 01'), ('brand/brand_mark/Logo-02.svg', 'Brand Mark 02'), ('brand/brand_mark/Logo-03.svg', 'Brand Mark 03')], default='brand/brand_mark/Logo-02.svg', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalsitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Optional: link to Google Maps location (normal URL).'),
        ),
    ]
