# Generated by Django 5.2.x on 2025-12-31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_alter_brandappearancesettings_logo_dark_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsitesettings",
            name="google_maps_url",
            field=models.URLField(blank=True, help_text="Optional: link to Google Maps location (for footer + contact)."),
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("menu_label", models.CharField(blank=True, default="The Menu", max_length=30)),
                ("primary_links", wagtail.fields.StreamField([("link", 0)], blank=True, use_json_field=True)),
                ("menu_links", wagtail.fields.StreamField([("link", 0)], blank=True, use_json_field=True)),
                ("header_cta", wagtail.fields.StreamField([("link", 0)], blank=True, max_num=1, use_json_field=True)),
                ("footer_links", wagtail.fields.StreamField([("link", 0)], blank=True, use_json_field=True)),
                ("site", models.OneToOneField(editable=False, on_delete=models.deletion.CASCADE, to="wagtailcore.site")),
            ],
            options={"abstract": False, "verbose_name": "Navigation"},
        ),
    ]
