# Generated by Django 5.2.9 on 2026-01-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_globalsitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandappearancesettings',
            name='paper_texture_enabled',
            field=models.BooleanField(default=True, help_text='Adds a subtle paper-like texture to the site background (works in light + dark mode).'),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='paper_texture_strength',
            field=models.PositiveSmallIntegerField(default=100, help_text='Texture strength (0–200). 100 is subtle and recommended.'),
        ),
    ]
