# Generated by Django 5.2.9 on 2026-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_brandappearancesettings_paper_texture_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandappearancesettings',
            name='body_font_size_px',
            field=models.PositiveSmallIntegerField(default=16, help_text='Base body font size in pixels (default 16).'),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='body_font_weight',
            field=models.PositiveSmallIntegerField(default=400, help_text='Work Sans variable font weight for body copy (e.g. 300–700). Default 400.'),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='heading_font_weight',
            field=models.PositiveSmallIntegerField(default=300, help_text='Heading font weight (Koh Santepheap). Default 300 to match current styling.'),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='ui_font_size_px',
            field=models.PositiveSmallIntegerField(default=15, help_text='Base UI font size in pixels for buttons/nav/labels (default 15).'),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='ui_font_weight',
            field=models.PositiveSmallIntegerField(default=300, help_text='UI font weight for components (default 300 to match nav/labels/headings).'),
        ),
    ]
