# Generated by Django 5.2.x on 2025-12-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_navigation_and_maps"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ga4_measurement_id", models.CharField(blank=True, help_text="GA4 Measurement ID (e.g. G-XXXXXXX). Loaded only with analytics consent.", max_length=32)),
                ("meta_pixel_id", models.CharField(blank=True, help_text="Meta Pixel ID. Loaded only with marketing consent.", max_length=32)),
                ("site", models.OneToOneField(editable=False, on_delete=models.deletion.CASCADE, to="wagtailcore.site")),
            ],
            options={"abstract": False, "verbose_name": "Analytics"},
        ),
    ]
