# Generated by Django 5.2.9 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_brandappearancesettings_body_font_size_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandappearancesettings',
            name='footer_logo_variant',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('mark', 'Mark')], default='primary', help_text='Logo variant to show in the footer.', max_length=20),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='secondary_logo_dark_path',
            field=models.CharField(blank=True, help_text="Static path under /static (e.g. 'brand/secondary/Logo-16.svg'). Used on dark theme.", max_length=255),
        ),
        migrations.AddField(
            model_name='brandappearancesettings',
            name='secondary_logo_light_path',
            field=models.CharField(blank=True, help_text="Static path under /static (e.g. 'brand/secondary/Logo-16.svg'). Used on light theme.", max_length=255),
        ),
    ]
