# Generated by Django 5.2.9 on 2026-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_update_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='booking_url',
            field=models.URLField(blank=True, help_text="Global booking URL (e.g. Fresha/ANS). Used as a fallback for 'Book Now' buttons."),
        ),
    ]
